In [10]:
# Built in method to create a list of values
nums_list = [*range(1, 12, 2)]
nums_list

[1, 3, 5, 7, 9, 11]

In [11]:
# Built in method to add an index
names = ['Mark', 'Sarah', 'Nicole', 'John']
indexed_names = [*enumerate(names, start=1)]
indexed_names

[(1, 'Mark'), (2, 'Sarah'), (3, 'Nicole'), (4, 'John')]

In [12]:
# Built in method to apply a function to every element of an object
names_map = map(str.upper, names)
names_upper = [*list(names_map)]
names_upper

['MARK', 'SARAH', 'NICOLE', 'JOHN']

In [13]:
# Numpy arrays
import numpy as np

nums = np.array([[1, 2, 3], [4, 5, 6]])
print(nums[1,:]) # print the second row of 2d array
print(nums[nums > 4]) # check for values above condition
nums_dbl = nums * 2 # doubles every element
print(nums_dbl)

nums[:,2] = nums[:,2] + 1 # add one to the third column of nums
print(nums)

[4 5 6]
[5 6]
[[ 2  4  6]
 [ 8 10 12]]
[[1 2 4]
 [4 5 7]]


In [14]:
# Combine a number of lists together efficiently using zip()
list1 = names
list2 = nums_list
zipped_list = [*zip(list1, list2)] # Combination only keeps the elements that match index values
print(*zipped_list)

('Mark', 1) ('Sarah', 3) ('Nicole', 5) ('John', 7)


In [15]:
# Counter()
# Taken from the collections package. This method helps to efficiently count the unique values requested and orders 
# the count output in a descending order
from collections import Counter

primary_types = ['grass', 'fire', 'water', 'ice', 'grass', 'normal', 'fire', 'water']
type_count = Counter(primary_types)
type_count

Counter({'grass': 2, 'fire': 2, 'water': 2, 'ice': 1, 'normal': 1})

In [16]:
# Combinations()
# Taken from the itertools package. Method is used to review the potential combinations that are 
# available from a list. You used combinations() from itertools to collect various combination-tuples 
# from a list. combinations() allows you to specify any size of combinations by passing 
# an integer as the second argument.
from itertools import combinations

names_new = names.copy()
names_new.append('Kelly')
names_new.append('Emma')
combos_obj = combinations(names_new, 2)
combos_obj_out = [*combos_obj]
print(combos_obj_out)

combos_4 = [*combinations(names_new, 4)]
print(combos_4)

[('Mark', 'Sarah'), ('Mark', 'Nicole'), ('Mark', 'John'), ('Mark', 'Kelly'), ('Mark', 'Emma'), ('Sarah', 'Nicole'), ('Sarah', 'John'), ('Sarah', 'Kelly'), ('Sarah', 'Emma'), ('Nicole', 'John'), ('Nicole', 'Kelly'), ('Nicole', 'Emma'), ('John', 'Kelly'), ('John', 'Emma'), ('Kelly', 'Emma')]
[('Mark', 'Sarah', 'Nicole', 'John'), ('Mark', 'Sarah', 'Nicole', 'Kelly'), ('Mark', 'Sarah', 'Nicole', 'Emma'), ('Mark', 'Sarah', 'John', 'Kelly'), ('Mark', 'Sarah', 'John', 'Emma'), ('Mark', 'Sarah', 'Kelly', 'Emma'), ('Mark', 'Nicole', 'John', 'Kelly'), ('Mark', 'Nicole', 'John', 'Emma'), ('Mark', 'Nicole', 'Kelly', 'Emma'), ('Mark', 'John', 'Kelly', 'Emma'), ('Sarah', 'Nicole', 'John', 'Kelly'), ('Sarah', 'Nicole', 'John', 'Emma'), ('Sarah', 'Nicole', 'Kelly', 'Emma'), ('Sarah', 'John', 'Kelly', 'Emma'), ('Nicole', 'John', 'Kelly', 'Emma')]


In [17]:
for i in dir():
    print(type(globals()[i]))
#     if type(globals()[i]) == pd.DataFrame:
#         print(type(globals()[i]))
#         print(i)

<class 'type'>
<class 'list'>
<class 'dict'>
<class 'collections.Counter'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'collections.Counter'>
<class 'list'>
<class 'list'>
<class 'collections.Counter'>
<class 'list'>
<class 'list'>
<class 'module'>
<class 'module'>
<class 'str'>
<class 'NoneType'>
<class 'str'>
<class 'NoneType'>
<class 'NoneType'>
<class 'list'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'list'>
<class 'str'>
<class 'str'>
<class 'dict'>
<class 'type'>
<class 'list'>
<class 'itertools.combinations'>
<class 'list'>
<class 'IPython.core.autocall.ZMQExitAutocall'>
<class 'method'>
<class 'str'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'map'>
<class 'list'>
<class 'list'>
<class 'module'>
<class 'numpy.ndarray'>

In [18]:
# Magic function will suppress the output within the jupyter cell
%%capture
!pip install pyathena

UsageError: Line magic function `%%capture` not found.


In [ ]:
!pip install pyathena